name: Deploy master branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn

      - name: Install serverless cli
        run: npm install -g serverless

      - name: Set aws credentials
        run: serverless config credentials --provider aws --key ${{ secrets.MY_AWS_ACCESS_KEY }} --secret ${{ secrets.MY_AWS_SECRET_ACCESS_KEY }}

      - name: serverless deploy
        run: yarn run deploy

      # - name: serverless deploy
      #   uses: serverless/github-action@master
      #   with:
      #     args: deploy --stage prod
      #   env:
      #     SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      #     AWS_ACCESS_KEY_ID: ${{ secrets.MY_AWS_ACCESS_KEY }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.MY_AWS_SECRET_ACCESS_KEY }}
